### ISSUE TITLE
/t doesn't work

### ISSUE THREAD

**Issue by TheAlexPlus** [patrickporto/twitch-chat#6]
## Describe the bug
when I try to use /t to send a message to twitch, i get an error that says /t isn't a chat command

## To Reproduce
1. try to use /t
2. see the error

## Expected behavior
I expected it to be a chat command

## Environment (please complete the following information):
 - Foundry VTT: 10.312
 - Browser: Chrome
 - Module Version: 11.0.0

**Comment by patrickporto** [comment]
Hi
Have you the [chat-commands](https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib) enabled on the world? Have you seen any relevant messages on the browser console?

**Comment by TheAlexPlus** [comment]
yea i have chat-commands enabled.

the error i get in the console is:

foundry.js:59246 Error: /t is not a valid chat message command.
    at ChatLog.processMessage (foundry.js:74517:40)
    at ChatLog._onChatKeyDown (foundry.js:74809:19)
    at HTMLTextAreaElement.jumpToMenuHandler (Autocomplete.mjs:111:21)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
fetch @ foundry.js:59246
foundry.js:74517 Uncaught (in promise) Error: /t is not a valid chat message command.
    at ChatLog.processMessage (foundry.js:74517:40)
    at ChatLog._onChatKeyDown (foundry.js:74809:19)
    at HTMLTextAreaElement.jumpToMenuHandler (Autocomplete.mjs:111:21)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
